"""model backends and user routes

Revision ID: 69a0df56ab66
Revises: c596f1a86342
Create Date: 2026-06-11 15:59:34.092465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a0df56ab66'
down_revision: Union[str, Sequence[str], None] = 'c596f1a86342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_backends',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=True),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_backends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_backends_name'), ['name'], unique=True)

    op.create_table('user_model_routes',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('backend_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_model_routes')
    with op.batch_alter_table('model_backends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_backends_name'))

    op.drop_table('model_backends')
    # ### end Alembic commands ###
