"""machine tools column

Revision ID: 78c84b4bf2e8
Revises: 69a0df56ab66
Create Date: 2026-06-11 16:35:20.526415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c84b4bf2e8'
down_revision: Union[str, Sequence[str], None] = '69a0df56ab66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tools', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_column('tools')

    # ### end Alembic commands ###
