"""initial schema

Revision ID: c596f1a86342
Revises: 
Create Date: 2026-06-11 12:15:13.151845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c596f1a86342'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('machine_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('requested_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('risk_rule', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_status'), ['status'], unique=False)

    op.create_table('enrollment_tokens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrollment_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollment_tokens_token_hash'), ['token_hash'], unique=True)

    op.create_table('machine_grants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('machine_id', sa.String(length=64), nullable=False),
    sa.Column('grantee_user_id', sa.String(length=64), nullable=False),
    sa.Column('granted_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machine_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_grants_grantee_user_id'), ['grantee_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machine_grants_machine_id'), ['machine_id'], unique=False)

    op.create_table('machines',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('machine_name', sa.String(length=255), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=True),
    sa.Column('os', sa.String(length=32), nullable=True),
    sa.Column('arch', sa.String(length=32), nullable=True),
    sa.Column('runner_version', sa.String(length=32), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('allowed_roots', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machines_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_token_hash'), ['token_hash'], unique=True)

    op.create_table('model_usage',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('backend_id', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_usage_backend_id'), ['backend_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_usage_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_usage_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('auth_tokens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('machine_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('machine_id', sa.String(length=64), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=False),
    sa.Column('stderr', sa.Text(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_session_id'), ['session_id'], unique=False)

    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('machine_id', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('arguments_json', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_calls_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_calls_session_id'))

    op.drop_table('tool_calls')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_messages_seq'))

    op.drop_table('messages')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_machine_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_machine_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_tokens_token_hash'))

    op.drop_table('auth_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('model_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_model_usage_session_id'))
        batch_op.drop_index(batch_op.f('ix_model_usage_backend_id'))

    op.drop_table('model_usage')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_token_hash'))
        batch_op.drop_index(batch_op.f('ix_machines_owner_user_id'))

    op.drop_table('machines')
    with op.batch_alter_table('machine_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_grants_machine_id'))
        batch_op.drop_index(batch_op.f('ix_machine_grants_grantee_user_id'))

    op.drop_table('machine_grants')
    with op.batch_alter_table('enrollment_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollment_tokens_token_hash'))

    op.drop_table('enrollment_tokens')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_approvals_machine_id'))

    op.drop_table('approvals')
    # ### end Alembic commands ###
